parser: typescript-eslint-parser
parserOptions: 
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures: 
    modules: true
plugins:
  - typescript
env: 
  browser: true
# globals:
  # 这里填入你的项目需要的全局变量
  # 这里值为 false 表示这个全局变量不允许被重新赋值，比如：
  # React: false,
  # ReactDOM: false
  # Vue: false
rules: 
  eqeqeq:
    - error
    - always
  indent:
    - error
    - 2
  quotes:
    - warn
    - single
  no-console:
    - warn
  no-unreachable:
    - error
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true
  max-len:
    - warn
    - code: 120
  'typescript/class-name-casing': 'error'