export const NODE_SIZE = 140;
export const CELL_SIZE = 300;
export const ARROW_OFFSET = 100; // 箭头距离图表原点
export const ARROW_HEIGHT = 10;
export const ARROW_WIDTH = 6;
export const CALLSTACK_HEIGHT = 12;
export const RULE_PADDING = 20; // 标尺左右补白
export const RULE_HEIGHT = 45;
export const RULE_STEP = 500;
export const ID_COMBINER = '-to-';